version: "3"
services:
  gatewayService:
    image: gateway:latest
    container_name: gateway-server
    ports:
      - "8099:8099"
      - "8089:8089"
    networks:
      - rpcnetwork

networks:
  rpcnetwork:
    external: true
