
pipeline {
    agent any

    stages {
        stage('stage: Pull Code'){
            steps {
             git branch: env.BRANCH_NAME, credentialsId: 'fangao-github', url: 'git@gitee.com:codegly/go-admin.git'
            }
        }

        stage('stage: Build Application'){
            steps {
                sh """
                    docker build -f ./authorize/docker/Dockerfile -t authorize --build-arg SVC1=${env.BRANCH_NAME} .
                """
            }
        }

        stage('stage: Deploy Application'){
            steps {
                sh """
                    docker-compose -f ./authorize/docker/docker-compose.yml down
                    docker-compose -f ./authorize/docker/docker-compose.yml up -d
                """
            }
        }
    }

    post {
        always{
            script{
                deleteDir()
            }
        }

        success{
            script{
                deleteDir()
            }

        }
        failure{
            script{
                deleteDir()
            }
        }

        aborted{
            script{
                deleteDir()
            }

        }
    }
}
