
pipeline {
    agent any
    environment {
        //以上自定义的参数
        __BRANCH = "main"
        __GIT_URL = "git@gitee.com:codegly/go-admin.git"
    }
    stages {
        stage('stage: Echo Env'){
            steps {
                echo "${__BRANCH}"
                echo "${__GIT_URL}"
            }
        }

        stage('stage: Pull Code'){
            steps {
             git branch: "${__BRANCH}", credentialsId: 'fangao-github', url: "${__GIT_URL}"
            }
        }

        stage('stage: Build Application'){
            steps {
                sh """
                    docker build -f ./authorize/docker/Dockerfile -t authorize --build-arg SVC1="${__BRANCH}" .
                """
            }
        }

        stage('stage: Deploy Application'){
            steps {
                sh """
                    docker-compose -f ./authorize/docker/docker-compose.yml down
                    docker-compose -f ./authorize/docker/docker-compose.yml up -d
                """
            }
        }
    }

    post {
        always{
            script{
                deleteDir()
            }
        }

        success{
            script{
                deleteDir()
            }

        }
        failure{
            script{
                deleteDir()
            }
        }

        aborted{
            script{
                deleteDir()
            }

        }
    }
}
