logger:
  #Level 0 紧急的 1警报 2重要的 3错误 4警告 5提示 6信息 7调试
  consoleShow: true
  consoleLevel:  7
  fileWrite:  false
  fileLevel:  7
  multiFileWrite: false
  multiFileLevel: 7

httpServer:
  port: 8099


rpcClient:
  clientName: "gateway"
  basePath: "go-admin-example"
  registerPlugin: "etcd"
  registerServers:
    - "192.168.101.24:2379"
  failRetryModel: 3
  balanceModel: 2
  poolSize: 1

tracer:
  openTrace: false
  traceName: "gateway"
  host: "127.0.0.1:6831"

analysisServer:
  type: "http"
  port: 8089
  serviceName: "gateway"
  prometheus: true
